In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Dataset/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [4]:
df[df.radius_mean >15]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.0,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.5,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
4,84358402,M,20.29,14.34,135.1,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.2,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN
6,844359,M,18.25,19.98,119.6,1040.0,0.09463,0.10900,0.11270,0.07400,...,27.66,153.2,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
563,926125,M,20.92,25.09,143.0,1347.0,0.10990,0.22360,0.31740,0.14740,...,29.41,179.1,1819.0,0.1407,0.4186,0.6599,0.2542,0.2929,0.09873,NaN
564,926424,M,21.56,22.39,142.0,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.1,2027.0,0.1410,0.2113,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.2,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.0,1731.0,0.1166,0.1922,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.3,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.7,1124.0,0.1139,0.3094,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.1,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.6,1821.0,0.1650,0.8681,0.9387,0.2650,0.4087,0.12400,NaN

In [5]:
df.radius_mean.min()

6.981

In [6]:
df.radius_mean.max()

28.11

In [7]:
df.loc[
    df.radius_mean >25
    
]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
82,8611555,M,25.22,24.91,171.5,1878.0,0.1063,0.2665,0.3339,0.1845,...,33.62,211.7,2562.0,0.1573,0.6076,0.6476,0.2867,0.2355,0.10510,NaN
180,873592,M,27.22,21.87,182.1,2250.0,0.1094,0.1914,0.2871,0.1878,...,32.85,220.8,3216.0,0.1472,0.4034,0.5340,0.2688,0.2856,0.08082,NaN
212,8810703,M,28.11,18.47,188.5,2499.0,0.1142,0.1516,0.3201,0.1595,...,18.47,188.5,2499.0,0.1142,0.1516,0.3201,0.1595,0.1648,0.05525,NaN
352,899987,M,25.73,17.46,174.2,2010.0,0.1149,0.2363,0.3368,0.1913,...,23.58,229.3,3234.0,0.1530,0.5937,0.6451,0.2756,0.3690,0.08815,NaN
461,911296202,M,27.42,26.27,186.9,2501.0,0.1084,0.1988,0.3635,0.1689,...,31.37,251.2,4254.0,0.1357,0.4256,0.6833,0.2625,0.2641,0.07427,NaN

In [8]:
# To choose certain columns simultaneously with the above filtering

df.loc[
    df.radius_mean > 25,
    ['radius_mean','texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean']
]

     radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean
82         25.22         24.91           171.5     1878.0           0.1063
180        27.22         21.87           182.1     2250.0           0.1094
212        28.11         18.47           188.5     2499.0           0.1142
352        25.73         17.46           174.2     2010.0           0.1149
461        27.42         26.27           186.9     2501.0           0.1084

### Using bitwise operators

In [9]:
# AND operator

df.loc[
    (df.diagnosis == 'M') & (df.radius_mean > 25),
    ['diagnosis','radius_mean','texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean']
    
]

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean
82,M,25.22,24.91,171.5,1878.0,0.1063
180,M,27.22,21.87,182.1,2250.0,0.1094
212,M,28.11,18.47,188.5,2499.0,0.1142
352,M,25.73,17.46,174.2,2010.0,0.1149
461,M,27.42,26.27,186.9,2501.0,0.1084

In [10]:
# OR operator

df.loc[
    (df.diagnosis == 'M') | (df.radius_mean > 25),
    ['diagnosis','radius_mean','texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean']
    
]

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean
0,M,17.99,10.38,122.80,1001.0,0.11840
1,M,20.57,17.77,132.90,1326.0,0.08474
2,M,19.69,21.25,130.00,1203.0,0.10960
3,M,11.42,20.38,77.58,386.1,0.14250
4,M,20.29,14.34,135.10,1297.0,0.10030
...,...,...,...,...,...,...
563,M,20.92,25.09,143.00,1347.0,0.10990
564,M,21.56,22.39,142.00,1479.0,0.11100
565,M,20.13,28.25,131.20,1261.0,0.09780
566,M,16.60,28.08,108.30,858.1,0.08455
567,M,20.60,29.33,140.10,1265.0,0.11780

In [11]:
# using between

df.loc[
    (df.diagnosis == 'M') | (df.radius_mean.between(24, 28) ),
    ['diagnosis','radius_mean','texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean']
    
]

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean
0,M,17.99,10.38,122.80,1001.0,0.11840
1,M,20.57,17.77,132.90,1326.0,0.08474
2,M,19.69,21.25,130.00,1203.0,0.10960
3,M,11.42,20.38,77.58,386.1,0.14250
4,M,20.29,14.34,135.10,1297.0,0.10030
...,...,...,...,...,...,...
563,M,20.92,25.09,143.00,1347.0,0.10990
564,M,21.56,22.39,142.00,1479.0,0.11100
565,M,20.13,28.25,131.20,1261.0,0.09780
566,M,16.60,28.08,108.30,858.1,0.08455
567,M,20.60,29.33,140.10,1265.0,0.11780

In [12]:
# isin() method. It tells if a particular value exists in a particular column
df.loc[
    df.radius_mean.isin([19.69]),
    ['diagnosis','radius_mean','texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean']
    
]

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean
2,M,19.69,21.25,130.0,1203.0,0.1096

#### Index of the maximum and minimum value of a given column

In [13]:
[df.radius_mean.idxmax(), df.radius_mean.idxmin()]

[212, 101]

In [14]:
df.loc[
    [df.radius_mean.idxmax(), df.radius_mean.idxmin()],
    ['diagnosis','radius_mean','texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean']
    
]

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean
212,M,28.110,18.47,188.50,2499.0,0.1142
101,B,6.981,13.43,43.79,143.5,0.1170

In [15]:
# grabing columns of a dataframe by passing a list to items:
df.filter(items=['diagnosis', 'radius_mean']).head()

  diagnosis  radius_mean
0         M        17.99
1         M        20.57
2         M        19.69
3         M        11.42
4         M        20.29

In [16]:
# use regular expressions; here, we select any columns that start with t:
df.filter(regex = r'^c').head()

,compactness_mean,concavity_mean,concave points_mean,compactness_se,concavity_se,concave points_se,compactness_worst,concavity_worst,concave points_worst
0,0.27760,0.3001,0.14710,0.04904,0.05373,0.01587,0.6656,0.7119,0.2654
1,0.07864,0.0869,0.07017,0.01308,0.01860,0.01340,0.1866,0.2416,0.1860
2,0.15990,0.1974,0.12790,0.04006,0.03832,0.02058,0.4245,0.4504,0.2430
3,0.28390,0.2414,0.10520,0.07458,0.05661,0.01867,0.8663,0.6869,0.2575
4,0.13280,0.1980,0.10430,0.02461,0.05688,0.01885,0.2050,0.4000,0.1625

In [20]:
df.set_index('id').title.filter(like='_mean').head()

AttributeError: 'DataFrame' object has no attribute 'title'