In [1]:
import numpy as np
import pandas as pd


df = pd.read_csv('Dataset/earthquakes.csv')

In [2]:
df.empty

False

In [3]:
df.shape

(9332, 26)

In [6]:
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url'],
      dtype='object')

In [4]:
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...

In [7]:
df.tail()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
9327,NaN,NaN,73086771,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01806,NaN,185.0,",nc73086771,",0.62,md,...,",nc,",reviewed,1537230228060,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1537285598315,https://earthquake.usgs.gov/earthquakes/eventp...
9328,NaN,NaN,38063967,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.03041,NaN,50.0,",ci38063967,",1.00,ml,...,",ci,",reviewed,1537230135130,"M 1.0 - 3km W of Julian, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537276800970,https://earthquake.usgs.gov/earthquakes/eventp...
9329,NaN,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.45260,NaN,276.0,",pr2018261000,",2.40,md,...,",pr,",reviewed,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...
9330,NaN,NaN,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01865,NaN,61.0,",ci38063959,",1.10,ml,...,",ci,",reviewed,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...
9331,NaN,NaN,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01698,NaN,39.0,",ci38063935,",0.66,ml,...,",ci,",reviewed,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...

In [8]:
df.dtypes

alert       object
cdi        float64
code        object
detail      object
dmin       float64
felt       float64
gap        float64
ids         object
mag        float64
magType     object
mmi        float64
net         object
nst        float64
place       object
rms        float64
sig          int64
sources     object
status      object
time         int64
title       object
tsunami      int64
type        object
types       object
tz         float64
updated      int64
url         object
dtype: object

### Getting information and finding Null values

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9332 entries, 0 to 9331
Data columns (total 26 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   alert    59 non-null     object
 1   cdi      329 non-null    float64
 2   code     9332 non-null   object
 3   detail   9332 non-null   object
 4   dmin     6139 non-null   float64
 5   felt     329 non-null    float64
 6   gap      6164 non-null   float64
 7   ids      9332 non-null   object
 8   mag      9331 non-null   float64
 9   magType  9331 non-null   object
 10  mmi      93 non-null     float64
 11  net      9332 non-null   object
 12  nst      5364 non-null   float64
 13  place    9332 non-null   object
 14  rms      9332 non-null   float64
 15  sig      9332 non-null   int64
 16  sources  9332 non-null   object
 17  status   9332 non-null   object
 18  time     9332 non-null   int64
 19  title    9332 non-null   object
 20  tsunami  9332 non-null   int64
 21  type     9332 non-null   object
 22  types    9332 non-null   object
 23  tz       9331 non-null   float64
 24  updated  9332 non-null   int64
 25  url      9332 non-null   object
dtypes: float64(9), int64(4), object(13)
memory usage: 1.9+ MB

### Getting summary of Statistics

In [11]:
df.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,329.000000,6139.000000,329.000000,6164.000000,9331.000000,93.000000,5364.000000,9332.000000,9332.000000,9.332000e+03,9332.000000,9331.000000,9.332000e+03
mean,2.754711,0.544925,12.310030,121.506588,1.497345,3.651398,19.053878,0.362122,56.899914,1.538284e+12,0.006537,-451.990140,1.538537e+12
std,1.010637,2.214305,48.954944,72.962363,1.203347,1.790523,15.492315,0.317784,91.872163,6.080306e+08,0.080589,231.752571,6.564135e+08
min,0.000000,0.000648,0.000000,12.000000,-1.260000,0.000000,0.000000,0.000000,0.000000,1.537229e+12,0.000000,-720.000000,1.537230e+12
25%,2.000000,0.020425,1.000000,66.142500,0.720000,2.680000,8.000000,0.119675,8.000000,1.537793e+12,0.000000,-540.000000,1.537996e+12
50%,2.700000,0.059050,2.000000,105.000000,1.300000,3.720000,15.000000,0.210000,26.000000,1.538245e+12,0.000000,-480.000000,1.538621e+12
75%,3.300000,0.177250,5.000000,159.000000,1.900000,4.570000,25.000000,0.590000,56.000000,1.538766e+12,0.000000,-480.000000,1.539110e+12
max,8.400000,53.737000,580.000000,355.910000,7.500000,9.120000,172.000000,1.910000,2015.000000,1.539475e+12,1.000000,720.000000,1.539537e+12

####  We can choose the percentiles we want to print
specifying 85th and 95th percentile

In [15]:
df.describe(percentiles=[0.85,0.95])

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,329.000000,6139.000000,329.000000,6164.000000,9331.000000,93.000000,5364.000000,9332.000000,9332.000000,9.332000e+03,9332.000000,9331.000000,9.332000e+03
mean,2.754711,0.544925,12.310030,121.506588,1.497345,3.651398,19.053878,0.362122,56.899914,1.538284e+12,0.006537,-451.990140,1.538537e+12
std,1.010637,2.214305,48.954944,72.962363,1.203347,1.790523,15.492315,0.317784,91.872163,6.080306e+08,0.080589,231.752571,6.564135e+08
min,0.000000,0.000648,0.000000,12.000000,-1.260000,0.000000,0.000000,0.000000,0.000000,1.537229e+12,0.000000,-720.000000,1.537230e+12
50%,2.700000,0.059050,2.000000,105.000000,1.300000,3.720000,15.000000,0.210000,26.000000,1.538245e+12,0.000000,-480.000000,1.538621e+12
85%,3.800000,0.542000,9.800000,200.856000,2.410000,5.176000,34.000000,0.740000,89.000000,1.539035e+12,0.000000,-420.000000,1.539228e+12
95%,4.300000,2.678900,40.200000,276.000000,4.400000,6.380000,49.000000,0.960000,298.000000,1.539319e+12,0.000000,-60.000000,1.539400e+12
max,8.400000,53.737000,580.000000,355.910000,7.500000,9.120000,172.000000,1.910000,2015.000000,1.539475e+12,1.000000,720.000000,1.539537e+12

##### Describing specific data types

In [18]:
df.describe(include=np.object_)

,alert,code,detail,ids,magType,net,place,sources,status,title,type,types,url
count,59,9332,9332,9332,9331,9332,9332,9332,9332,9332,9332,9332,9332
unique,2,9332,9332,9332,10,14,5433,52,2,7807,5,42,9332
top,green,20272018,https://earthquake.usgs.gov/fdsnws/event/1/que...,",nc73094766,",ml,ak,"10km NE of Aguanga, CA",",ak,",reviewed,"M 0.4 - 10km NE of Aguanga, CA",earthquake,",geoserve,origin,phase-data,",https://earthquake.usgs.gov/earthquakes/eventp...
freq,58,1,1,1,6803,3166,306,2981,7797,55,9081,5301,1

In [19]:
df.describe(include='all')

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
count,59,329.000000,9332,9332,6139.000000,329.000000,6164.000000,9332,9331.000000,9331,...,9332,9332,9.332000e+03,9332,9332.000000,9332,9332,9331.000000,9.332000e+03,9332
unique,2,NaN,9332,9332,NaN,NaN,NaN,9332,NaN,10,...,52,2,NaN,7807,NaN,5,42,NaN,NaN,9332
top,green,NaN,20272018,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",nc73094766,",NaN,ml,...,",ak,",reviewed,NaN,"M 0.4 - 10km NE of Aguanga, CA",NaN,earthquake,",geoserve,origin,phase-data,",NaN,NaN,https://earthquake.usgs.gov/earthquakes/eventp...
freq,58,NaN,1,1,NaN,NaN,NaN,1,NaN,6803,...,2981,7797,NaN,55,NaN,9081,5301,NaN,NaN,1
mean,NaN,2.754711,NaN,NaN,0.544925,12.310030,121.506588,NaN,1.497345,NaN,...,NaN,NaN,1.538284e+12,NaN,0.006537,NaN,NaN,-451.990140,1.538537e+12,NaN
std,NaN,1.010637,NaN,NaN,2.214305,48.954944,72.962363,NaN,1.203347,NaN,...,NaN,NaN,6.080306e+08,NaN,0.080589,NaN,NaN,231.752571,6.564135e+08,NaN
min,NaN,0.000000,NaN,NaN,0.000648,0.000000,12.000000,NaN,-1.260000,NaN,...,NaN,NaN,1.537229e+12,NaN,0.000000,NaN,NaN,-720.000000,1.537230e+12,NaN
25%,NaN,2.000000,NaN,NaN,0.020425,1.000000,66.142500,NaN,0.720000,NaN,...,NaN,NaN,1.537793e+12,NaN,0.000000,NaN,NaN,-540.000000,1.537996e+12,NaN
50%,NaN,2.700000,NaN,NaN,0.059050,2.000000,105.000000,NaN,1.300000,NaN,...,NaN,NaN,1.538245e+12,NaN,0.000000,NaN,NaN,-480.000000,1.538621e+12,NaN
75%,NaN,3.300000,NaN,NaN,0.177250,5.000000,159.000000,NaN,1.900000,NaN,...,NaN,NaN,1.538766e+12,NaN,0.000000,NaN,NaN,-480.000000,1.539110e+12,NaN
max,NaN,8.400000,NaN,NaN,53.737000,580.000000,355.910000,NaN,7.500000,NaN,...,NaN,NaN,1.539475e+12,NaN,1.000000,NaN,NaN,720.000000,1.539537e+12,NaN

In [20]:
df.felt.describe() # For the felt column

count    329.000000
mean      12.310030
std       48.954944
min        0.000000
25%        1.000000
50%        2.000000
75%        5.000000
max      580.000000
Name: felt, dtype: float64

In [22]:
df.ids.describe() # For the ids column

count             9332
unique            9332
top       ,nc73094766,
freq                 1
Name: ids, dtype: object

In [23]:
df.felt.unique()

array([ nan,  28.,   1.,  11.,   7.,  13.,   9.,  64.,  19.,   3.,   6.,
         2.,  15.,  59.,   5.,   4.,   8., 170.,  10.,  54., 157.,  25.,
        33.,  17.,   0., 185.,  23., 580.,  18., 198., 488., 101.,  38.,
       155.,  20.,  39.,  12.,  14.,  41., 159.,  27.,  63., 179.,  53.,
        85.])